# Site settings
title: Ricardo Jorge Gil Ramos - Personal Page
email: jorgegilramos@jorgegilramos.es
description: ""
baseurl: "/web"
url: "http://jorgegilramos.github.io"

exclude: [node_modules, CNAME, webpack.config.js, package.json, README.md, .git]
sass:
  sass_dir: assets/css
  style: :compressed
  
include:
  - .nojekyll

collections:
  areas:
    output: true

